# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_final.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(412, 244)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 394, 224))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_result = QtWidgets.QLabel(self.layoutWidget)
        self.title_result.setMinimumSize(QtCore.QSize(141, 31))
        self.title_result.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_result.setFont(font)
        self.title_result.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 0, 0);\n"
"\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"\n"
"color: rgb(0, 0, 255)\n"
"")
        self.title_result.setAlignment(QtCore.Qt.AlignCenter)
        self.title_result.setObjectName("title_result")
        self.verticalLayout.addWidget(self.title_result)
        self.result = QtWidgets.QLabel(self.layoutWidget)
        self.result.setMinimumSize(QtCore.QSize(141, 90))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.result.setFont(font)
        self.result.setStyleSheet("border: 1px solid rgb(85, 0, 0);\n"
"color:#fff;\n"
"background-color: rgb(247, 56, 59)")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_camera = QtWidgets.QLabel(self.layoutWidget)
        self.title_camera.setMinimumSize(QtCore.QSize(241, 31))
        self.title_camera.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_camera.setFont(font)
        self.title_camera.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 0, 0);\n"
"\n"
"\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"\n"
"color: rgb(0, 0, 255)\n"
"")
        self.title_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.title_camera.setObjectName("title_camera")
        self.verticalLayout_3.addWidget(self.title_camera)
        self.camera = QtWidgets.QLabel(self.layoutWidget)
        self.camera.setMinimumSize(QtCore.QSize(241, 181))
        self.camera.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 0, 0);\n"
"\n"
"\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"\n"
"color: rgb(0, 0, 255)\n"
"")
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.verticalLayout_3.addWidget(self.camera)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_quantity = QtWidgets.QLabel(self.layoutWidget)
        self.title_quantity.setMinimumSize(QtCore.QSize(141, 31))
        self.title_quantity.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_quantity.setFont(font)
        self.title_quantity.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 0, 0);\n"
"\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"\n"
"color: rgb(0, 0, 255)\n"
"")
        self.title_quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.title_quantity.setObjectName("title_quantity")
        self.verticalLayout_2.addWidget(self.title_quantity)
        self.quantity = QtWidgets.QLabel(self.layoutWidget)
        self.quantity.setMinimumSize(QtCore.QSize(141, 60))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.quantity.setFont(font)
        self.quantity.setStyleSheet("border: 1px solid rgb(85, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.quantity.setText("")
        self.quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity.setObjectName("quantity")
        self.verticalLayout_2.addWidget(self.quantity)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_result.setText(_translate("Form", "RESULT"))
        self.result.setText(_translate("Form", "NG CAM S4-190"))
        self.title_camera.setText(_translate("Form", "CAMERA"))
        self.title_quantity.setText(_translate("Form", "Quantity"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
