# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rh189_area_c.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 272)
        Form.setMinimumSize(QtCore.QSize(566, 251))
        Form.setFocusPolicy(QtCore.Qt.ClickFocus)
        Form.setAutoFillBackground(False)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(300, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 238))
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.result = QtWidgets.QLabel(self.frame_2)
        self.result.setMinimumSize(QtCore.QSize(110, 90))
        self.result.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.result.setFont(font)
        self.result.setStyleSheet("background-color: rgb(221, 221, 110);\n"
"border: 1px solid rgb(85, 0, 0);\n"
"margin-bottom: 24px;")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.gridLayout_2.addWidget(self.result, 2, 0, 1, 1)
        self.title_result = QtWidgets.QLabel(self.frame_2)
        self.title_result.setMinimumSize(QtCore.QSize(110, 31))
        self.title_result.setMaximumSize(QtCore.QSize(150, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_result.setFont(font)
        self.title_result.setStyleSheet("background-color: rgb(63, 63, 63);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"color: rgb(255, 255, 255)")
        self.title_result.setAlignment(QtCore.Qt.AlignCenter)
        self.title_result.setObjectName("title_result")
        self.gridLayout_2.addWidget(self.title_result, 1, 0, 1, 1)
        self.btn_update = QtWidgets.QPushButton(self.frame_2)
        self.btn_update.setMinimumSize(QtCore.QSize(0, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_update.setPalette(palette)
        self.btn_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_update.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_update.setStyleSheet("QPushButton {\n"
"    background-color: #00b5ad;\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"    font: 14pt \"Impact\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #008c86;\n"
"}\n"
"\n"
"")
        self.btn_update.setAutoDefault(False)
        self.btn_update.setDefault(False)
        self.btn_update.setFlat(False)
        self.btn_update.setObjectName("btn_update")
        self.gridLayout_2.addWidget(self.btn_update, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(426, 238))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setContentsMargins(1, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.title_camera = QtWidgets.QLabel(self.frame_3)
        self.title_camera.setMinimumSize(QtCore.QSize(200, 31))
        self.title_camera.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_camera.setFont(font)
        self.title_camera.setStyleSheet("background-color: rgb(63, 63, 63);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"color: rgb(255, 255, 255)")
        self.title_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.title_camera.setObjectName("title_camera")
        self.gridLayout.addWidget(self.title_camera, 0, 0, 1, 1)
        self.title_camera_2 = QtWidgets.QLabel(self.frame_3)
        self.title_camera_2.setMinimumSize(QtCore.QSize(200, 31))
        self.title_camera_2.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_camera_2.setFont(font)
        self.title_camera_2.setStyleSheet("background-color: rgb(63, 63, 63);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"color: rgb(255, 255, 255)")
        self.title_camera_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_camera_2.setObjectName("title_camera_2")
        self.gridLayout.addWidget(self.title_camera_2, 0, 1, 1, 1)
        self.camera = QtWidgets.QLabel(self.frame_3)
        self.camera.setMinimumSize(QtCore.QSize(200, 181))
        self.camera.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 0, 0);\n"
"\n"
"\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"\n"
"color: rgb(0, 0, 255)\n"
"")
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.gridLayout.addWidget(self.camera, 1, 0, 1, 1)
        self.camera_2 = QtWidgets.QLabel(self.frame_3)
        self.camera_2.setMinimumSize(QtCore.QSize(200, 181))
        self.camera_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 0, 0);\n"
"\n"
"\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"\n"
"color: rgb(0, 0, 255)\n"
"")
        self.camera_2.setText("")
        self.camera_2.setObjectName("camera_2")
        self.gridLayout.addWidget(self.camera_2, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.result.setText(_translate("Form", "WAIT"))
        self.title_result.setText(_translate("Form", "Result"))
        self.btn_update.setText(_translate("Form", "Update"))
        self.title_camera.setText(_translate("Form", "Camera 1"))
        self.title_camera_2.setText(_translate("Form", "Camera 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
