# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_areaC.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(409, 239)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(391, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_result = QtWidgets.QLabel(self.frame)
        self.title_result.setMinimumSize(QtCore.QSize(141, 31))
        self.title_result.setMaximumSize(QtCore.QSize(160, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_result.setFont(font)
        self.title_result.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 0, 0);\n"
"\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"\n"
"color: rgb(0, 0, 255)\n"
"")
        self.title_result.setAlignment(QtCore.Qt.AlignCenter)
        self.title_result.setObjectName("title_result")
        self.gridLayout_2.addWidget(self.title_result, 0, 0, 1, 1)
        self.title_camera = QtWidgets.QLabel(self.frame)
        self.title_camera.setMinimumSize(QtCore.QSize(241, 31))
        self.title_camera.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_camera.setFont(font)
        self.title_camera.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 0, 0);\n"
"\n"
"\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"\n"
"color: rgb(0, 0, 255)\n"
"")
        self.title_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.title_camera.setObjectName("title_camera")
        self.gridLayout_2.addWidget(self.title_camera, 0, 1, 1, 1)
        self.result = QtWidgets.QLabel(self.frame)
        self.result.setMinimumSize(QtCore.QSize(141, 181))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.result.setFont(font)
        self.result.setStyleSheet("border: 1px solid rgb(85, 0, 0);\n"
"color:#fff;\n"
"background-color: rgb(247, 56, 59)")
        self.result.setText("")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.gridLayout_2.addWidget(self.result, 1, 0, 1, 1)
        self.camera = QtWidgets.QLabel(self.frame)
        self.camera.setMinimumSize(QtCore.QSize(241, 181))
        self.camera.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 0, 0);\n"
"\n"
"\n"
"font-weight: 600;\n"
"font: 14pt \"Impact\";\n"
"\n"
"color: rgb(0, 0, 255)\n"
"")
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.gridLayout_2.addWidget(self.camera, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_result.setText(_translate("Form", "RESULT"))
        self.title_camera.setText(_translate("Form", "CAMERA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
