# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(467, 350)
        Form.setStyleSheet("")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 461, 335))
        self.frame_2.setMinimumSize(QtCore.QSize(440, 335))
        self.frame_2.setStyleSheet("\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 120, 291))
        self.groupBox_3.setMinimumSize(QtCore.QSize(120, 260))
        self.groupBox_3.setStyleSheet("background-color: #e7e7e7;\n"
"border-radius: 8px;\n"
"border: 1px solid #ccc")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 120, 40))
        self.label_3.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 8px 8px 0 0;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"background-color: #fff;\n"
"color: rgb(0, 85, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 100, 40))
        self.label_4.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 8px 8px 0 0;\n"
"background-color: #fff\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(136, 10, 321, 291))
        self.groupBox.setMinimumSize(QtCore.QSize(248, 280))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setToolTip("")
        self.groupBox.setStyleSheet("background-color: #e7e7e7;\n"
"border: 1px solid #ccc;\n"
"border-radius: 8px 8px 8px 8px;\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 321, 40))
        self.label_2.setMinimumSize(QtCore.QSize(230, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 8px 8px 0 0;\n"
"background-color: #fff;\n"
"color: rgb(0, 85, 255);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 50, 301, 227))
        self.label.setMinimumSize(QtCore.QSize(274, 227))
        self.label.setSizeIncrement(QtCore.QSize(274, 245))
        self.label.setStyleSheet("border-radius: 0 0 8px 8px;\n"
"border: 1px solid #ccc;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(41, 0, 390, 40))
        self.label_5.setMinimumSize(QtCore.QSize(390, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 85, 255);\n"
"border: 1px solid #ccc;\n"
"border-radius: 8px 8px 0 0;\n"
"background-color: #fff;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "RESULT"))
        self.label_4.setText(_translate("Form", "wait"))
        self.label_2.setText(_translate("Form", "CAMERA"))
        self.label_5.setText(_translate("Form", "SCAN CÂN TRỌNG LƯỢNG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
