plc_scan = b'4'
plc_scan_receive = b'4'
sfc_weighted = b'4'
sfc_weighted_demo = b'4'
sfc_weighted_receive = b''
machine_weighted = b'4'
sfc_OK = b'1'
sfc_OK_receive = b'\x01\x00'
sfc_NG = b'2'
sfc_NG_receive = b'\x02\x00'
NG_cam = b'2'
plc_reset = b'3'
plc_reset_receive = b'\x03\x00'

# test

plc_test_reset = b'3'
plc_test_scan = b'4'
sfc_test_ok = b'1'
sfc_test_ng = b'2'

machine_OKOK = b'5'
machine_NGOK = b'6'
machine_OKNG = b'7'
machine_NGNG = b'8'
#
status_pass = 'PASS'
status_wait = 'WAIT'
status_ng_sfc = 'NG SFC'
status_ng_cam = 'NG CAM'
status_reset = 'RESET'
status_ng_cam_s4_190 = 'NG CAM S4-190'
status_ng_sfc_s4_190 = 'NG SFC S4-190'

# plc_scan = b'4'
# plc_scan_receive = b'\x004'
# sfc_weighted = b'4\r\n'
# sfc_weighted_receive = b'\x04\x00'
# machine_weighted = b'4\r\n'
# sfc_OK = b'1\r\n'
# sfc_OK_receive = b'\x01\x00'
# sfc_NG = b'2\r\n'
# sfc_NG_receive = b'\x02\x00'

plc_reset = b'3\r\n'
plc_reset_receive = b'\x03\x00'
cam_NG = b'3\r\n'
machine_OKOK = b'5\r\n'
machine_NGOK = b'6\r\n'
machine_OKNG = b'7\r\n'
machine_NGNG = b'8\r\n'

s4_190_scan = b'4'
s4_190_OK = b'1'
s4_190_NG = b'2'
s4_190_NG_cam = b'3'
s4_200_OK = b'1'
s4_200_NG = b'2'
s4_200_NG_cam = b'0'

timer = 3